site_name: raSCSI NAT-less wifi
site_url: https://example.com/
theme:
    name: readthedocs
nav:
    - Home: index.md
    - Raspi OS Image: raspios.md
    - Install rascsi: rascsi.md
    - Mount hda image: hdaimage.md
    - Systemd-networkd: sysdnetd.md
    - Proxy Arp: proxyarp.md
    - Rasci bridge: rascsibridge.md
    - Daynaport: daynaport.md
    - Mac software installs: macsw.md
    - References: ref.md
    
markdown_extensions:
  - attr_list
