site_name: raSCSI NAT-less wifi
site_url: https://example.com/
nav:
    - Home: index.md
    - Raspi OS Image: raspios.md
    - Install rascsi: rascsi.md
    - Mount hda image: hdaimage.md
    - Systemd-networkd: sysdnetd.md
    - Proxy Arp: proxyarp.md
    - Rasci bridge: rascsibridge.md
    - Danaport: danaport.md
    - TCP/IP: tcpip.md
    
